### Read all movies
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### READ ALL FILTERED
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films/?minimum-duration=10

### READ ONE
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films/3

### Créer un nouveau film
POST http://localhost:3000/films
Content-Type: application/json

{
  "id": 4,
  "title": "Nouveau Film",
  "director": "Réalisateur 4",
  "duration": 140,
  "budget": 15,
  "description": "Un autre super film",
  "imageUrl": "http://image.com/4"
}

### Lire tous les films avec pagination (page 2, limite 2)
GET http://localhost:3000/films?page=1&limit=5

### Filtrer les films par titre (rechercher les films qui contiennent "Film")
GET http://localhost:3000/films?title=Film

### Trier les films par durée (ascendant)
GET http://localhost:3000/films?sortBy=duration&order=asc

### Trier les films par budget (descendant)
GET http://localhost:3000/films?sortBy=budget&order=desc

### Combiner pagination, tri par durée (ascendant) et filtrage par titre
GET http://localhost:3000/films?page=1&limit=5&sortBy=duration&order=asc&title=Film